name: Create release
on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '14.0'
          - '13.3'
          - '13.2'
          - '12.4'
        include:
          - repo: http://pkg.FreeBSD.org/${ABI}/latest
          - repoesc: http:\/\/pkg.FreeBSD.org\/${ABI}\/latest
          - repoprefix: "pkg+"
          - gitargs: "--depth=1"

          
          - repo: http://mirror.sg.gs/freebsd-pkg/${ABI}/latest
            repoesc: http:\/\/mirror.sg.gs\/freebsd-pkg\/${ABI}\/latest
            repoprefix: ""
            gitargs: "--depth=1 --branch release/12.4.0"
            version: '12.4'
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        shell: bash
        run: |
          mkdir repo
          sed -i "s/^export VM_INSTALL_CMD$/export VM_INSTALL_CMD=\$'mkdir -p \/usr\/local\/etc\/pkg\/repos \&\& echo \\\\'FreeBSD: { url: \"${{ matrix.mirrorprefix }}"'${{ matrix.repoesc }}'"\" }\\\\' > \/usr\/local\/etc\/pkg\/repos\/FreeBSD.conf \&\& pkg  install  -y '/" /home/runner/work/_actions/vmactions/freebsd-vm/v*/run.sh
          echo "$(</home/runner/work/_actions/vmactions/freebsd-vm/v*/run.sh )"
      - name: Build
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.version }}
          sync: sshfs
          usesh: true
          prepare: |
            mkdir -p /usr/local/etc/pkg/repos
            echo 'FreeBSD: { url: "${{ matrix.mirrorprefix }}${{ matrix.repo }}" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
            pkg install -y git
          run: |
            mkdir -p /usr/local/etc/pkg/repos
            echo 'FreeBSD: { url: "${{ matrix.mirrorprefix }}${{ matrix.repo }}" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
            set -e -x
            git clone ${{ matrix.gitargs }} https://git.FreeBSD.org/ports.git /usr/ports
            pkg install -y `make -C /usr/ports/www/vaultwarden-web_vault build-depends-list | awk '{gsub(/^.*\//,"");ORS=FS;}1; END{print "\n"}'`
            make -C /usr/ports/www/vaultwarden-web_vault install BATCH=yes
            pkg create -o /usr/ports/packages/All vaultwarden_web-vault
            pkg install -y `make -C /usr/ports/security/vaultwarden build-depends-list | awk '{gsub(/^.*\//,"");ORS=FS;}1; END{print "\n"}'`
            make -C /usr/ports/security/vaultwarden install BATCH=yes
            pkg create -o /usr/ports/packages/All vaultwarden
            pkg repo /usr/ports/packages
            cp -R /usr/ports/packages "${GITHUB_WORKSPACE}/repo"
      - name: temp control
        shell: sh
        run: |
          echo `ls repo`
