name: Create release
on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.version }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86-64, arm64]
        os: [freebsd]
        version:
          - '13.3'
          - '13.2'
          - '13.1'
          - '13.0'
          - '12.4'
          - '12.2'
        exclude:
          - version: '12.2'
            arch: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir repo
      - name: Build with cross-platform-actions
        if: ${{ matrix.version != '14.0' }}
        uses: cross-platform-actions/action@v0.24.0
        with:
          operating_system: ${{ matrix.os }}
          architecture: ${{ matrix.arch }}
          version: ${{ matrix.version }}
          shell: sh
          run: |
            mkdir -p /usr/local/etc/pkg/repos
            echo 'FreeBSD: { url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
            pkg install -y git
            git clone https://git.FreeBSD.org/ports.git /usr/ports
            pkg install -y `make -C /usr/ports/www/vaultwarden-web_vault build-depends-list | awk '{gsub(/^.*\//,"");ORS=FS;}1; END{print "\n"}'`
            make -C /usr/ports/www/vaultwarden-web_vault install BATCH=yes
            pkg create -o /usr/ports/packages/All vaultwarden_web-vault
            pkg install -y `make -C /usr/ports/security/vaultwarden build-depends-list | awk '{gsub(/^.*\//,"");ORS=FS;}1; END{print "\n"}'`
            make -C /usr/ports/security/vaultwarden install BATCH=yes
            pkg create -o /usr/ports/packages/All vaultwarden
            pkg repo /usr/ports/packages
            cp -R /usr/ports/packages ~/repo
      - name: Build with vmactions
        if: ${{ matrix.version == '14.0' }}
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.version }}
          sync: sshfs
          usesh: true
          prepare: |
            mkdir -p /usr/local/etc/pkg/repos
            echo 'FreeBSD: { url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
            pkg install -y git
          run: |
            mkdir -p /usr/local/etc/pkg/repos
            echo 'FreeBSD: { url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
            set -e -x
            git clone https://git.FreeBSD.org/ports.git /usr/ports
            pkg install -y `make -C /usr/ports/www/vaultwarden-web_vault build-depends-list | awk '{gsub(/^.*\//,"");ORS=FS;}1; END{print "\n"}'`
            make -C /usr/ports/www/vaultwarden-web_vault install BATCH=yes
            pkg create -o /usr/ports/packages/All vaultwarden_web-vault
            pkg install -y `make -C /usr/ports/security/vaultwarden build-depends-list | awk '{gsub(/^.*\//,"");ORS=FS;}1; END{print "\n"}'`
            make -C /usr/ports/security/vaultwarden install BATCH=yes
            pkg create -o /usr/ports/packages/All vaultwarden
            pkg repo /usr/ports/packages
            cp -R /usr/ports/packages ~/repo
      - name: temp control
        run: |
          ls repo
